version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: agent_inc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/agent_inc?sslmode=disable
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy

  generic_agent:
    build:
      context: ./agents/generic_agent
      dockerfile: Dockerfile
    image: agentic-engineering-system_generic_agent
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  postgres_data:
