// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenericAgent_ExecuteTask_FullMethodName = "/agent.GenericAgent/ExecuteTask"
)

// GenericAgentClient is the client API for GenericAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition for the Generic Agent.
type GenericAgentClient interface {
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResult, error)
}

type genericAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGenericAgentClient(cc grpc.ClientConnInterface) GenericAgentClient {
	return &genericAgentClient{cc}
}

func (c *genericAgentClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, GenericAgent_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenericAgentServer is the server API for GenericAgent service.
// All implementations must embed UnimplementedGenericAgentServer
// for forward compatibility.
//
// The service definition for the Generic Agent.
type GenericAgentServer interface {
	ExecuteTask(context.Context, *TaskRequest) (*TaskResult, error)
	mustEmbedUnimplementedGenericAgentServer()
}

// UnimplementedGenericAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenericAgentServer struct{}

func (UnimplementedGenericAgentServer) ExecuteTask(context.Context, *TaskRequest) (*TaskResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedGenericAgentServer) mustEmbedUnimplementedGenericAgentServer() {}
func (UnimplementedGenericAgentServer) testEmbeddedByValue()                      {}

// UnsafeGenericAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenericAgentServer will
// result in compilation errors.
type UnsafeGenericAgentServer interface {
	mustEmbedUnimplementedGenericAgentServer()
}

func RegisterGenericAgentServer(s grpc.ServiceRegistrar, srv GenericAgentServer) {
	// If the following call pancis, it indicates UnimplementedGenericAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenericAgent_ServiceDesc, srv)
}

func _GenericAgent_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericAgentServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenericAgent_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericAgentServer).ExecuteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenericAgent_ServiceDesc is the grpc.ServiceDesc for GenericAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenericAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.GenericAgent",
	HandlerType: (*GenericAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _GenericAgent_ExecuteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
