# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"A\n\x0eSubTaskRequest\x12\x19\n\x11requested_persona\x18\x01 \x01(\t\x12\x14\n\x0ctask_details\x18\x02 \x01(\t\"\xc0\x01\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x16\n\x0epersona_prompt\x18\x02 \x01(\t\x12\x19\n\x11task_instructions\x18\x03 \x01(\t\x12\x39\n\x0c\x63ontext_data\x18\x04 \x03(\x0b\x32#.agent.TaskRequest.ContextDataEntry\x1a\x32\n\x10\x43ontextDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x86\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x15\n\rfinal_content\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12(\n\tsub_tasks\x18\x05 \x03(\x0b\x32\x15.agent.SubTaskRequest2F\n\x0cGenericAgent\x12\x36\n\x0b\x45xecuteTask\x12\x12.agent.TaskRequest\x1a\x11.agent.TaskResult\"\x00\x42\"Z agentic-engineering-system/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z agentic-engineering-system/proto'
  _globals['_TASKREQUEST_CONTEXTDATAENTRY']._loaded_options = None
  _globals['_TASKREQUEST_CONTEXTDATAENTRY']._serialized_options = b'8\001'
  _globals['_SUBTASKREQUEST']._serialized_start=22
  _globals['_SUBTASKREQUEST']._serialized_end=87
  _globals['_TASKREQUEST']._serialized_start=90
  _globals['_TASKREQUEST']._serialized_end=282
  _globals['_TASKREQUEST_CONTEXTDATAENTRY']._serialized_start=232
  _globals['_TASKREQUEST_CONTEXTDATAENTRY']._serialized_end=282
  _globals['_TASKRESULT']._serialized_start=285
  _globals['_TASKRESULT']._serialized_end=419
  _globals['_GENERICAGENT']._serialized_start=421
  _globals['_GENERICAGENT']._serialized_end=491
# @@protoc_insertion_point(module_scope)
